server:
  port: 8763

spring:
  application:
    name: una-consumer
  cloud:
    nacos:
      username: nacos
      password: nacos

      discovery:
        server-addr: localhost:8848
        service: una-consumer
        namespace: prod
      config:
        server-addr: localhost:8848
        file-extension: yaml
        #指定分组
        group: prod
        #指定命名空间
        namespace: prod

    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748

# 通过feign.sentinel.enable开启Feign和sentinel的自动适配
feign:
  sentinel:
    enabled: true
