server:
  port: 8763

spring:
  application:
    name: una-consumer
  cloud:
    nacos:
      username: nacos
      password: nacos

      discovery:
        server-addr: localhost:8848
        service: una-consumer
        namespace: test
      config:
        server-addr: localhost:8848
        file-extension: yaml
        #指定分组
        group: test
        #指定命名空间
        namespace: test
