server:
  port: 8763

spring:
  application:
    name: una-consumer
  cloud:
    nacos:
      username: nacos
      password: nacos

      discovery:
        server-addr: localhost:8848 # 192.168.0.6:8848 # docker容器版nacos使用
        service: una-consumer
        namespace: dev
      config:
        server-addr: localhost:8848 # 192.168.0.6:8848 # docker容器版nacos使用
        file-extension: yaml
        #指定分组
        group: dev
        #指定命名空间
        namespace: dev

    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748

  # Spring Cloud Sleuth+zipkin实现链路追踪
  sleuth:
    sampler:
      # 设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: una-consumer

# 通过feign.sentinel.enable开启Feign和sentinel的自动适配
feign:
  sentinel:
    enabled: true

#==============================knife4j配置=======================================
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # 配置文件的作用是增加swagger密码访问的权限 访问查看此模块接口 需要输入下面用户名和密码
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin
