# 配置管理-配置列表
# 配置组 prod | 配置ID una-consumer-prod.yaml
server:
  port: 8763

spring:
  application:
    name: una-consumer
  cloud:
    nacos:
      username: nacos
      password: nacos

      discovery:
        server-addr: localhost:8848
        service: una-consumer
        namespace: prod
      config:
        server-addr: localhost:8848
        file-extension: yaml
        #指定分组
        group: prod
        #指定命名空间
        namespace: prod

    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748

  # Spring Cloud Sleuth+zipkin实现链路追踪
  sleuth:
    sampler:
      # 设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: una-consumer

# 通过feign.sentinel.enable开启Feign和sentinel的自动适配
feign:
  sentinel:
    enabled: true

diyName: LC-prod
