server:
  port: 8090

spring:
  application:
    name: una-admin

  cloud:
    nacos:
      username: nacos
      password: nacos

      discovery:
        server-addr: localhost:8848
        service: una-admin
        namespace: prod
      config:
        server-addr: localhost:8848
        file-extension: yaml
        #指定分组
        group: prod
        #指定命名空间
        namespace: prod

  # Spring Cloud Sleuth+zipkin实现链路追踪
  sleuth:
    sampler:
      # 设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: una-admin

  # ======================================================================mysql begin 要想切换到mysql配置 只需在 begin end中所有选择 ctrl+/即可
  # mysql数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://##.14.##.65:3306/u-na?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ###
  # ======================================================================mysql end

#==============================knife4j配置=======================================
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # 配置文件的作用是增加swagger密码访问的权限 访问查看此模块接口 需要输入下面用户名和密码
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin
