server:
  port: 8090

spring:
  application:
    name: una-admin

  cloud:
    nacos:
      username: nacos
      password: nacos

      discovery:
        server-addr: localhost:8848
        service: una-admin
        namespace: dev
      config:
        server-addr: localhost:8848
        file-extension: yaml
        #指定分组
        group: dev
        #指定命名空间
        namespace: dev

  # Spring Cloud Sleuth+zipkin实现链路追踪
  sleuth:
    sampler:
      # 设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: una-admin

  # ======================================================================mysql begin 要想切换到mysql配置 只需在 begin end中所有选择 ctrl+/即可
  # mysql数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://##.14.##.65:3306/u-na?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ###
  # ======================================================================mysql end

#==============================knife4j配置=======================================
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # 配置文件的作用是增加swagger密码访问的权限 访问查看此模块接口 需要输入下面用户名和密码
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin

#==============================mybatis配置=======================================
mybatis-plus:
  # xml文件在resources文件夹内【una-admin/src/main/resources/mapper/AdminMapper.xml】路径配置方式【mapper/*Mapper.xml】
  # mapper-locations: mapper/*Mapper.xml
  # 在属性文件中【una-admin/src/main/java/com/lc/una/admin/mapper/AdminMapper.xml】指定xml文件路径 路径配置方式【classpath:com/lc/una/admin/mapper/*.xml】
  # 默认值：["classpath*:/mapper/**/*.xml"]
  # Maven 多模块项目的扫描路径需以 classpath*: 开头 （即加载多个 jar 包下的 XML 文件）
  mapper-locations: classpath:com/lc/una/xo/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lc.una.commons.entity
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断" 此版本取消了field-strategy配置项
      # field-strategy: NOT_EMPTY
      # 驼峰下划线转换
      # column-underline: true
      table-underline: true
      # 数据库大写下划线转换
      # capital-mode: true
      # mp2.3+ 全局表前缀 mp_
      # table-prefix: mp_
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      # 如果插件版本是3.0-gamma这个选项必须配置,否则会nullPoint 目前这个版本没有此配置项
      # db-type=oracle
    # 刷新mapper 调试神器 此版本没有这个配置项
    # refresh: true
  # 原生配置
  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
