# 这里其实不需要再次配置
# bootstrap.yml 可在rnacos的配置中心进行配置
# 配置管理-配置列表
# 配置组 dev | 配置ID una-provider-dev.yaml
# 然后将下面的内容 拷贝过去即可
server:
  port: 8762

spring:
  application:
    name: una-provider

  cloud:
    nacos:
      username: nacos # nacos的账号 这里rnacos配置了 也没事
      password: nacos # nacos的密码
      discovery:
        server-addr: localhost:8848
        service: una-provider
        namespace: dev
      config:
        server-addr: localhost:8848
        file-extension: yaml
        #指定分组
        group: dev
        #指定命名空间
        namespace: dev

  # Spring Cloud Sleuth+zipkin实现链路追踪
  sleuth:
    sampler:
      # 设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: una-provider

diyName: LC-dev
