# 配置管理-配置列表
# 配置组 prod | 配置ID una-provider-prod.yaml
# 注意-需要在命名空间 prod 下进行创建
server:
  port: 8762

spring:
  application:
    name: una-provider

  cloud:
    nacos:
#      username: nacos
#      password: nacos

      discovery:
        server-addr: localhost:8848
        service: una-provider
        namespace: prod
      config:
        server-addr: localhost:8848
        file-extension: yaml
        #指定分组
        group: prod
        #指定命名空间
        namespace: prod

  # Spring Cloud Sleuth+zipkin实现链路追踪
  sleuth:
    sampler:
      # 设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: una-provider

diyName: LC-prod
